context:
  version: 0.11.3
  python_min: "3.9"

package:
  name: rich-toolkit
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/rich-toolkit/rich_toolkit-${{ version }}.tar.gz
  sha256: 042cee58083e0bcbb56a69514b56a5def853ad064f977b6b95519087e4d9f239

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - rich
    - click 
    - typing_extensions

tests:
  - python:
      imports:
        - rich_toolkit
      pip_check: true
      python_version: 

about:
  homepage: https://github.com/patrick91/rich-toolkit
  summary: Rich toolkit for building command-line applications
  license: MIT
  license_file: LICENSE
  repository: https://github.com/patrick91/rich-toolkit

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/70829
    reason: Dependency for chromadb
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - synapticarbors
